apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster
  sources:
    - repoURL: https://github.com/mvs5465/local-k8s-apps
      targetRevision: HEAD
      ref: values

    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.3.0
      chart: grafana
      helm:
        releaseName: grafana
        valueFiles:
          - $values/helm/grafana/values.yaml
          - $values/helm/grafana/dashboards/cluster-overview.yaml
          - $values/helm/grafana/dashboards/loki-metrics.yaml
          - $values/helm/grafana/dashboards/pod-metrics.yaml
          - $values/helm/grafana/dashboards/argocd-overview.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
