apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.53.0
    chart: loki
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 24h
            ingestion_rate_mb: 4
            ingestion_burst_size_mb: 6

        singleBinary:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          persistence:
            enableStatefulSetAutoDeletePVC: true
            size: 1Gi

        ingress:
          enabled: false

        gateway:
          enabled: false

        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        test:
          enabled: false

        lokiCanary:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
