apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.x
    helm:
      releaseName: chat
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: ghcr.io/open-webui/open-webui
                  tag: main
                env:
                  - name: OLLAMA_BASE_URL
                    value: "http://ollama.ai.svc.cluster.local:11434"
                  - name: WEBUI_AUTH
                    value: "false"

        service:
          main:
            controller: main
            ports:
              http:
                port: 8080

        ingress:
          main:
            enabled: true
            className: nginx
            hosts:
              - host: chat.lan
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http

  destination:
    server: https://kubernetes.default.svc
    namespace: ai

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
