apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://twin.github.io/helm-charts
    targetRevision: 1.5.0
    chart: gatus
    helm:
      releaseName: gatus
      values: |
        replicaCount: 1

        image:
          repository: twinproduction/gatus
          tag: latest

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        ingress:
          enabled: true
          ingressClassName: nginx
          path: /
          pathType: Prefix
          hosts:
            - gatus.local

        persistence:
          enabled: true
          size: 500Mi
          mountPath: /data

        config:
          storage:
            type: sqlite
            path: /data/gatus.db

          ui:
            title: Service Status

          endpoints:
            - name: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200"

            - name: grafana
              url: http://grafana.monitoring.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200"

            - name: loki
              url: http://loki.monitoring.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200"

            - name: homepage
              url: http://homepage.services.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200"

            - name: argocd
              url: https://argocd.argocd.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200 || [STATUS] == 307"

            - name: gatus
              url: https://gatus.services.svc.cluster.local
              interval: 60s
              conditions:
                - "[STATUS] == 200 || [STATUS] == 307"

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
