apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
spec:
  refreshPolicy:
    type: Interval
    interval: 1h
  secretStoreRef:
    name: outline-secrets-store
    kind: SecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret-key: "{{ .secret_key }}"
        utils-secret: "{{ .utils_secret }}"
        postgres-password: "{{ .postgres_password }}"
        database-url: "postgresql://{{ .postgres_user }}:{{ .postgres_password }}@outline-postgres-0:5432/{{ .postgres_db }}"
  data:
  - secretKey: secret_key
    sourceRef:
      key: secret_key
  - secretKey: utils_secret
    sourceRef:
      key: utils_secret
  - secretKey: postgres_password
    sourceRef:
      key: postgres_password
  - secretKey: postgres_user
    sourceRef:
      key: postgres_user
  - secretKey: postgres_db
    sourceRef:
      key: postgres_db
