apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.x
    helm:
      releaseName: outline
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: outlinewiki/outline
                  tag: latest
                securityContext:
                  runAsUser: 0
                env:
                  # Core Outline configuration
                  - name: NODE_ENV
                    value: "production"
                  - name: URL
                    value: "http://outline.lan"
                  - name: SECRET_KEY
                    valueFrom:
                      secretKeyRef:
                        name: outline-secrets
                        key: secret-key
                  - name: UTILS_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: outline-secrets
                        key: utils-secret
                  # Database configuration
                  - name: DATABASE_URL
                    valueFrom:
                      secretKeyRef:
                        name: outline-secrets
                        key: database-url
                  # Redis configuration (required by Outline)
                  - name: REDIS_URL
                    value: "redis://outline-redis:6379"
                  # Redis for collaboration service (required by Outline for real-time collaboration)
                  - name: REDIS_COLLABORATION_URL
                    value: "redis://outline-redis:6379"
                  # Collaboration URL (required by Outline for real-time collaboration)
                  - name: COLLABORATION_URL
                    value: "http://outline-main:3000"
                  # File storage (local filesystem)
                  - name: FILE_STORAGE
                    value: "local"
                  - name: FILE_STORAGE_LOCAL_ROOT_DIR
                    value: "/data/files"
                  # SSL configuration for database
                  - name: PGSSLMODE
                    value: "disable"
                  # Logging
                  - name: LOG_LEVEL
                    value: "debug"
                resources:
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  limits:
                    cpu: 500m
                    memory: 1Gi

          postgres:
            type: statefulset
            containers:
              main:
                image:
                  repository: postgres
                  tag: "16-alpine"
                env:
                  - name: POSTGRES_USER
                    value: "outline"
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: outline-secrets
                        key: postgres-password
                  - name: POSTGRES_DB
                    value: "outline"
                  - name: PGDATA
                    value: "/var/lib/postgresql/data/pgdata"
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi

          redis:
            containers:
              main:
                image:
                  repository: redis
                  tag: "7-alpine"
                command:
                  - redis-server
                  - "--appendonly"
                  - "yes"
                  - "--dir"
                  - "/redis-data"
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 100m
                    memory: 128Mi

        service:
          main:
            controller: main
            ports:
              http:
                port: 3000
          postgres:
            controller: postgres
            type: ClusterIP
            clusterIP: None  # Headless service for StatefulSet
            ports:
              postgres:
                port: 5432
          redis:
            controller: redis
            ports:
              redis:
                port: 6379

        ingress:
          main:
            enabled: true
            className: nginx
            hosts:
              - host: outline.lan
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http

        persistence:
          data:
            enabled: true
            type: hostPath
            hostPath: /var/lib/colima/mnt/mac/Users/matthewschwartz/outline
            advancedMounts:
              main:
                main:
                  - path: /data
          postgres-data:
            enabled: true
            type: hostPath
            hostPath: /var/lib/colima/mnt/mac/Users/matthewschwartz/outline/postgres
            advancedMounts:
              postgres:
                main:
                  - path: /var/lib/postgresql/data
          redis-data:
            enabled: true
            type: emptyDir
            advancedMounts:
              redis:
                main:
                  - path: /redis-data

  destination:
    server: https://kubernetes.default.svc
    namespace: outline

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
