apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://helm.irsigler.cloud
    targetRevision: 4.0.0
    chart: uptime-kuma
    helm:
      releaseName: uptime-kuma
      values: |
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: kuma.local
              paths:
                - path: /
                  pathType: Prefix

        volume:
          size: 1Gi

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
