apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://charts.js.wiki
    chart: requarks/wiki
    targetRevision: 2.3.0
    helm:
      releaseName: wikijs
      values: |
        image:
          tag: "2"

        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: wiki.lan
              paths:
                - path: /
                  pathType: Prefix

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Disable chart-managed PVC — using hostPath instead
        persistence:
          enabled: false

        # Mount writable hostPath volume for wiki data
        volumes:
          - name: wiki-data
            hostPath:
              path: /var/lib/colima/mnt/mac/Users/matthewschwartz/wikijs
              type: DirectoryOrCreate

        volumeMounts:
          - name: wiki-data
            mountPath: /wiki/data

        # PostgreSQL for database (chart-managed PVC is fine here)
        postgresql:
          enabled: true
          persistence:
            enabled: true
            size: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
