apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cluster

  source:
    repoURL: https://github.com/mvs5465/local-k8s-apps
    targetRevision: main
    path: apps/jobs

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
